Repository DiyorMarket/CheckDrive.Web, pull requests merged in 2024-12, with the labels that each got.

#234 DoctorReviews page
  CheckDrive.Web/CheckDrive.Web/Views/DoctorReviews/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/wwwroot/css/site.css
Labels: Task

#231 Update employee page
  CheckDrive.Web/CheckDrive.Web/Views/Accounts/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Dashboard/Index.cshtml
Labels: Task

#228 bugs fixed
  CheckDrive.Web/CheckDrive.Web/Views/Accounts/Create.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Accounts/Edit.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Accounts/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Cars/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/OilMarks/Create.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/OilMarks/Edit.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/OilMarks/Index.cshtml
Labels: bug

#247 search and filter using javascript
  CheckDrive.Web/CheckDrive.Web/Views/Accounts/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Cars/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Debts/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/DispatcherReviews/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/DoctorReviews/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/MechanicAcceptances/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/MechanicHandovers/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/OperatorReviews/Index.cshtml
Labels: enhancement
