Repository DiyorMarket/CheckDrive.Web, pull requests merged in 2024-05, with the labels that each got.

#12 Create Models
  .github/workflows/dotnet.yml
  CheckDrive.Web/CheckDrive.Web/CheckDrive.Web.csproj
  CheckDrive.Web/CheckDrive.Web/Controllers/HomeController.cs
  CheckDrive.Web/CheckDrive.Web/Models/Account.cs
  CheckDrive.Web/CheckDrive.Web/Models/Car.cs
  CheckDrive.Web/CheckDrive.Web/Models/Dispatcher.cs
  CheckDrive.Web/CheckDrive.Web/Models/DispatcherReview.cs
  CheckDrive.Web/CheckDrive.Web/Models/Doctor.cs
  CheckDrive.Web/CheckDrive.Web/Models/DoctorReview.cs
  CheckDrive.Web/CheckDrive.Web/Models/Driver.cs
  CheckDrive.Web/CheckDrive.Web/Models/ErrorViewModel.cs
  CheckDrive.Web/CheckDrive.Web/Models/Mechanic.cs
  CheckDrive.Web/CheckDrive.Web/Models/MechanicAcceptance.cs
  CheckDrive.Web/CheckDrive.Web/Models/MechanicHandover.cs
  CheckDrive.Web/CheckDrive.Web/Models/Operator.cs
  CheckDrive.Web/CheckDrive.Web/Models/OperatorReview.cs
  CheckDrive.Web/CheckDrive.Web/Models/Role.cs
  CheckDrive.Web/CheckDrive.Web/Models/Status.cs
  CheckDrive.Web/CheckDrive.Web/Models/Technician.cs
  CheckDrive.Web/CheckDrive.Web/Views/Shared/Error.cshtml
Labels: good first issue

#14 Create response
  CheckDrive.Web/CheckDrive.Web/Responses/GetAccountResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetBaseResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetCarResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetDispatcherResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetDispatcherReviewResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetDoctorResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetDoctorReviewResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetMechanicAcceptanceResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetMechanicHandoverResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetMechanicResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetOperatorResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetOperatorReviewResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetRoleResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetTechnicianResponse.cs
Labels: Task

#16 Generate dashboard page for admin
  CheckDrive.Web/CheckDrive.Web/CheckDrive.Web.csproj
  CheckDrive.Web/CheckDrive.Web/Controllers/DashboardController.cs
  CheckDrive.Web/CheckDrive.Web/Program.cs
  CheckDrive.Web/CheckDrive.Web/Views/Dashboard/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_Layout.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_SideBar.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/_ViewImports.cshtml
  CheckDrive.Web/CheckDrive.Web/wwwroot/css/site.css
Labels: Task

#21 Generate Api Exceptions
  CheckDrive.Web/CheckDrive.Web/Exceptions/ApiException.cs
  CheckDrive.Web/CheckDrive.Web/Filters/ApiExceptionFilter.cs
  CheckDrive.Web/CheckDrive.Web/Program.cs
Labels: Task

#23 Create Configurations file for constants
  CheckDrive.Web/CheckDrive.Web/Constants/Configurations.cs
  CheckDrive.Web/CheckDrive.Web/Program.cs
Labels: Task

#26 Generate ApiClient for connect with API
  CheckDrive.Web/CheckDrive.Web/Models/Driver.cs
  CheckDrive.Web/CheckDrive.Web/Service/ApiClient.cs
Labels: Task

#27 Add configure data stores for mapping
  CheckDrive.Web/CheckDrive.Web/Extensions/ConfigureServiceExtensions.cs
  CheckDrive.Web/CheckDrive.Web/Program.cs
Labels: Task

#31 Upgrade syncfusion key
  CheckDrive.Web/CheckDrive.Web/CheckDrive.Web.csproj
  CheckDrive.Web/CheckDrive.Web/Constants/Configurations.cs
Labels: enhancement

#32 Add example data for Dashboard
  CheckDrive.Web/CheckDrive.Web/Controllers/DashboardController.cs
  CheckDrive.Web/CheckDrive.Web/Views/Dashboard/Index.cshtml
Labels: Task

#34 Update-sidebar
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_SideBar.cshtml
  CheckDrive.Web/CheckDrive.Web/wwwroot/css/site.css
Labels: enhancement

#35 Generate Haydovchi page for Admin
  CheckDrive.Web/CheckDrive.Web/CheckDrive.Web.csproj
  CheckDrive.Web/CheckDrive.Web/Controllers/AccountsController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/DriversController.cs
  CheckDrive.Web/CheckDrive.Web/Extensions/ConfigureServiceExtensions.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetDriverResponse.cs
  CheckDrive.Web/CheckDrive.Web/Service/ApiClient.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Accounts/AccountDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Accounts/IAccountDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Accounts/MockAccountDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Drivers/DriverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Drivers/IDriverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Drivers/MockDriverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Roles/IRoleDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Roles/MockRoleDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Roles/RoleDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Views/Drivers/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_Layout.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_SideBar.cshtml
  CheckDrive.Web/CheckDrive.Web/wwwroot/css/site.css
Labels: Task

#37 Generate operator page for admin
  CheckDrive.Web/CheckDrive.Web/CheckDrive.Web.csproj
  CheckDrive.Web/CheckDrive.Web/Controllers/AccountsController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/DashboardController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/DriversController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/OperatorReviewsController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/OperatorsController.cs
  CheckDrive.Web/CheckDrive.Web/Extensions/ConfigureServiceExtensions.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetOperatorReviewResponse.cs
  CheckDrive.Web/CheckDrive.Web/Service/ApiClient.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Accounts/AccountDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Accounts/IAccountDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/OperatorReviews/IOperatorReviewDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/OperatorReviews/MockOperatorReviewDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/OperatorReviews/OperatorReviewDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Operators/IOperatorDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Operators/MockOperatorDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Operators/OperatorDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Views/Accounts/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/OperatorReviews/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_SideBar.cshtml
Labels: Task

#42 Mechanic
  CheckDrive.Web/CheckDrive.Web.sln
  CheckDrive.Web/CheckDrive.Web/CheckDrive.Web.csproj
  CheckDrive.Web/CheckDrive.Web/Controllers/AccountsController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/DriversController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/MechanicAcceptancesController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/MechanicHandoversController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/MechanicsController.cs
  CheckDrive.Web/CheckDrive.Web/Controllers/OperatorReviewsController.cs
  CheckDrive.Web/CheckDrive.Web/Extensions/ConfigureServiceExtensions.cs
  CheckDrive.Web/CheckDrive.Web/Program.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetMechanicAcceptanceResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetMechanicHandoverResponse.cs
  CheckDrive.Web/CheckDrive.Web/Responses/GetMechanicResponse.cs
  CheckDrive.Web/CheckDrive.Web/Service/ApiClient.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Accounts/AccountDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Accounts/IAccountDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Drivers/DriverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Drivers/IDriverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/MechanicAcceptances/IMechanicAcceptanceDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/MechanicAcceptances/MechanicAcceptanceDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/MechanicAcceptances/MockMechanicAcceptanceDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/MechanicHandovers/IMechanicHandoverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/MechanicHandovers/MechanicHandoverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/MechanicHandovers/MockMechanicHandoverDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Mechanics/IMechanicDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Mechanics/MechanicDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Mechanics/MockMechanicDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Stores/Roles/RoleDataStore.cs
  CheckDrive.Web/CheckDrive.Web/Views/Drivers/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/MechanicAcceptances/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/MechanicHandovers/Index.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_Layout.cshtml
  CheckDrive.Web/CheckDrive.Web/Views/Shared/_SideBar.cshtml
Labels: enhancement
